# Generated by Django 4.2.6 on 2023-10-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="phone",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="record",
            name="zipcode",
            field=models.IntegerField(),
        ),
    ]
